### ISSUE TITLE
Enum as its own schema

### ISSUE THREAD

**Issue by sztyup** [samchon/nestia#1058]
## Feature Request
I would like to have enums not generated in the swagger as an inline type string schema with enum values but as its own schema element, that can be reused and have its own name.
This same functionality is supported by the builtin NestJs swagger generator: https://docs.nestjs.com/openapi/types-and-parameters#enums-schema

If you can give me a few pointers I can try to come up with a PR.

### Example method
```
enum AnimalEnum {
    Cat,
    Dog
}

interface RequestBody {
    animal: AnimalEnum
}
public function exampleRequest(@TypedBody() body: RequestBody)
```
### Expected output
```
"requestBody": {
  "content": {
    "application/json": {
      "schema": {
        "type": "object",
        "properties": {
          "animal": {
            "$ref": "#/components/schemas/AnimalEnum"
          }
        }
      }
    }
  }
},
```
```
"components": {
  "schemas": {
    "AnimalEnum": {
      "type": "string",
      "enum": [
        "Cat",
        "Dog"
       ]
    },
  }
},
```
### Actual output
```
"requestBody": {
  "content": {
    "application/json": {
      "schema": {
        "type": "object",
        "properties": {
          "animal": {
            "type": "string",
            "enum": [
                "Cat",
                "Dog"
            ]
          }
        }
      }
    }
  }
},
```

**Comment by samchon** [comment]
Solved in v6 and v7 updates.

**Comment by iROOT** [comment]
Hi @sztyup and @samchon,

I'm still seeing this issue in the latest versions of `@nestia/core` and `@nestia/sdk`. While the issue was marked as solved, enums are still being inlined instead of being generated as separate schemas with `$ref` references.  This prevents proper generation of API clients from Swagger definitions, as tools often rely on `$ref` for shared types.

I've created a minimal reproduction repository that demonstrates this issue: https://github.com/iROOT/nestia-swagger-enum-ref

The repository includes a simple NestJS application with an enum defined in a DTO.  When the Swagger schema is generated using `@nestia/sdk`, the enum values are inlined within the schema for the DTO properties, instead of generating a reusable `$ref` to a dedicated schema definition for the enum itself.

Could you please take a look at the reproduction and advise on whether there's a configuration issue on my end, or if this is indeed a regression or unresolved bug?  Thanks!

**Comment by sztyup** [comment]
Yes, I still see this bug with the latest version @samchon can you please reopen this issue?
